### ISSUE TITLE
Errore di sintassi in definizione openAPI ri_to_bo

### ISSUE THREAD

**Issue by falbesano** [AgID/specifiche-tecniche-DPR-160-2010#105]
Buongiormo,
segnalo un errore di sintassi (stringa non chiusa) in questa riga della definizione openAPI:

https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4096598d0cdf3ad63ae1dfc62ea14a1da7db77d7/openAPI/ri_to_bo.yaml#L222

Cordiali saluti
Federico

**Comment by AnaclerioRiccardo** [comment]
Questo errore è presente solamente sul branch main, sul branch mantaince001 questo errore di sintassi era già stato corretto 
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/ede22844c384b8b1a348e954b3650a439599864b/openAPI/ri_to_bo.yaml#L540
