### ISSUE TITLE
Fixing auditing for ET

### ISSUE THREAD

**Issue by AnaclerioRiccardo** [AgID/specifiche-tecniche-DPR-160-2010#106]
Nell’OpenAPI “catalogo-ssu_to_et.yaml” inserire il riferimento all’ente terzo che inoltra il messaggio all’interno dell’AuditMessage per l’opzione negative_outcome_sended cambiandola con quanto segue negative_outcome_sended_from_[0-9]{1,10} così come è stato fatto per il positive_outcome_sended_from_[0-9]{1,10}
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4f570b82d17dec5272bcf8aab37207e67f86b2f3/openAPI/catalogo-ssu_to_et.yaml#L191

**Comment by MicheleRagnatela** [comment]
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/110

**Comment by francescodiperna** [comment]
Buongiorno, cosa rappresenta il "codice ente terzo" indicato nel suffisso [0-9]{1,10}?
