### ISSUE TITLE
Fixing sample into OpenAPI

### ISSUE THREAD

**Issue by AnaclerioRiccardo** [AgID/specifiche-tecniche-DPR-160-2010#107]
Effettuare un consolidamento e/o aggiunta di esempi nelle OpenAPI al fine di diminuire i misunderstanding interpretativi delle stesse.
Come ad esempio per le seguenti casistiche:
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4f570b82d17dec5272bcf8aab37207e67f86b2f3/openAPI/catalogo-ssu_meta.yaml#L1933
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4f570b82d17dec5272bcf8aab37207e67f86b2f3/openAPI/catalogo-ssu_meta.yaml#L1946

**Comment by MicheleRagnatela** [comment]
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/110
