### ISSUE TITLE
Aggiunta attributo “state” all’entità “competent_administration”

### ISSUE THREAD

**Issue by AnaclerioRiccardo** [AgID/specifiche-tecniche-DPR-160-2010#108]
Aggiungere l’attributo “state” all’entità “competent_administration” all’interno del CatalogoSSU così da uniformarlo alle altre entità (es: fo_system, bo_system, third_party_system...), questo semplificherebbe anche il recupero dello stato dell’amministrazione competente nell’OpenAPI meta per il path “/competent-administrations-systems/{id_competent_administrations_list}”

**Comment by vintra73** [comment]
La presente issue non determina varazioni sulle OpenAPI implementate dalle componenti del SSU.

Si resta in attesa della valutazioni di merito da parte Infocamere, quale implementatore del Catalogo SSU, sull'opportunità/necessità di modificare il data model dello stesso catagolo.

**Comment by nirubino** [comment]
soluzione proposta #117
