### ISSUE TITLE
BO to ET identificazione mittente retry

### ISSUE THREAD

**Issue by nirubino** [AgID/specifiche-tecniche-DPR-160-2010#116]
in un procedimento unico in cui esiste una molteplicità 1:N tra cui e enti terzi la componente  BO SUAP non è in grado di identificare la componente ente terzo che l'ha chiamato

SI propone di aggiungere all'operation  retry del servizio BO to ET la terna che identifica l'amministrazione che la richiede (ipacode, officecode, version)

**Comment by nirubino** [comment]
soluzione proposta #117

**Comment by FCiminelliACN** [comment]
Tale issue risulta essere già segnalata nella issue https://github.com/AgID/specifiche-tecniche-DPR-160-2010/issues/111 e la relativa proposta di soluzione è stata definita nella seguente PR: [fix issue 111 - aggiunta requester_administration by FCiminelliACN · Pull Request #112 · AgID/specifiche-tecniche-DPR-160-2010 (github.com)](https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/112)

**Comment by vintra73** [comment]
@nirubino se condividi cancelliamo la seguente issue in considerazione dell'osservazione di @FCiminelliACN

**Comment by nirubino** [comment]
@vintra73 concordo con la cancellazione della issue
