### ISSUE TITLE
CATALOGO - METADATI; ERROR_404_001

### ISSUE THREAD

**Issue by LucaMontano** [AgID/specifiche-tecniche-DPR-160-2010#118]
Good afternoon,
I tried to send a request to the /typologies-lifeevents endpoint of the version 2 of "CATALOGO - METADATI" API for my administration, but I received:

`{
  "code": "ERROR_404_001",
  "message": "resource not found"
}`

every time. I found this document: https://catalogo.impresainungiorno.gov.it/assets/config/files/manuale_operativo_Eservice_CatalogoSSU.pdf and I tried to use data I found there, but I cannot obtain data successfully. The endpoint I'm using is https://casa.catalogocl.impresainungiorno.it/catalogo/typologies-lifeevents?municipality=07009001&lifeevent=apertura

Can you tell me if the endpoint I'm using is right or what can be the problem of the error above?

Thank you.

Luca Montano

**Comment by nirubino** [comment]
Per segnalazioni che riguardano il funzionamento delle API si rimanda al portale di supporto:
https://supporto.infocamere.it/aswsWeb/search?query=&idProduct=SICA&userRole=sicaut#

**Comment by vintra73** [comment]
@LucaMontano se la risposta di @nirubino la reputa conclusiva provvediamo a chiudere la presente issue
