### ISSUE TITLE
Eliminazione costrutto "discriminator" su tipi enum differenti

### ISSUE THREAD

**Issue by nicolalaginestra** [AgID/specifiche-tecniche-DPR-160-2010#126]
Al fine di ottenere una più corretta definizione delle interfacce prodotte dai tool di generazione dei client per l'api notify dell'e-service fo_to_bo si chiede l'eliminazione del costrutto discriminator sul tipo event poiché in realtà si tratta di due enumerati che di fatto sono differenti.

**Comment by FCiminelliACN** [comment]
Al fine di valutare la correttazza del costrutto "discriminator", posso chiedere informazioni circa il tool di generazione in uso?

**Comment by nicolalaginestra** [comment]
Il client viene generato con il plugin ufficiale di OpenAPI per Maven e come libreria di processing GSON
