### ISSUE TITLE
Specifiche tecniche - versione consolidata

### ISSUE THREAD

**Issue by ARIA-DMontedoro** [AgID/specifiche-tecniche-DPR-160-2010#134]
Stiamo sviluppando il componente integrativo SUAP da ente terzo per conto di Regione Lombardia. E' previsto che il nostro sviluppo si integri col sistema suap entro Luglio 2025.
Come comunicatoci in altra sede stiamo prendendo come branch di riferimento l'approved01. Stiamo riscontriamo modifiche in corso su altri branch. 
Possiamo considerare la versione attualmente presente su Approved01 come definitiva per fine Luglio 2025? 
Se così non fosse, quando saranno consolidati definitivamente i servizi e i flussi previsti dal sistema SUAP?

**Comment by FCiminelliACN** [comment]
Si ricorda che la piattaforma GitHub è stata creata con lo scopo di gestire le proposte di aggiornamento e miglioramento delle Specifiche Tecniche. Tali proposte possono essere create solamente dai membri del Gruppo Tecnico, costituito come indicato dal decreto interministeriale del 26 settembre 2023 SUAP (pubblicato in Gazzetta ufficiale n. 276 del 25 novembre 2023).

Considerata la natura della segnalazione, la invitiamo a riproporla negli opportuni canali di supporto gestiti da Dipartimento della Funzione Pubblica.
