### ISSUE TITLE
Richiesta info: Elaborazione istanze

### ISSUE THREAD

**Issue by ARIA-DMontedoro** [AgID/specifiche-tecniche-DPR-160-2010#136]
Come possiamo simulare una send_instance contente dati processabili successivamente dal client di sviluppo visibile sulla PDND di collaudo “SVIL - SSU BO to ET” e "CATALOGO - GESTIONE ISTANZA - ENTI TERZI"?
Potete fornirci un insieme di request congruenti ai dati presenti in collaudo?
Potete fornirci documentazione completa che descrive il workflow di utilizzo della Suite Black Box di collaudo "ACCREDITAMENTO SUAP ED ENTI-TERZI - SUITE DI BLACK-BOX-TEST"? In quanto non è definita la descrizione dei campi richiesti dagli e-service.
Riepilogando, sarebbe utile ottenere esempi di istanze:
1.	Si chiede un esempio di send_instance, cioè del body della call all’Ente Terzo.
2.	Request_integration (Richiesta di integrazione):
2.1.	Si chiede un esempio di oggetto RequestIntegrationRequest, quindi della richiesta di integrazione come creata da noi Ente Terzo.
2.2.	[Da documentazione](https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/approved01/sequence-diagram/SCIA-001.mermaid) riscontriamo che una volta soddisfatta la richiesta di integrazione si riceve una send_instance. Il cui di questa nuova istanza è lo stesso dell’istanza di partenza? Si chiede un esempio di send_instance successiva all’integrazione.
2.3.	Una volta soddisfatta la richiesta di integrazione l’instanceDescriptor può variare in tutti i suoi campi? Ci sono dei campi specifici che varieranno (es: versione?)
2.4.	Un Ente Terzo può inviare più richieste di integrazione contestualmente alla stessa istanza? Per inviarne una seconda, deve necessariamente aspettare che sia conclusa la richiesta precedente?
2.5.	C’è un numero limite di integrazioni richiedibili sulla stessa istanza?
3.	Send_conclusion (Conclusione):
3.1.	Si chiede un esempio di SendConclusionRequests (cioè invio dell'esito) nei casi di richiesta di conformazione, richiesta di sospensione, parere negativo e parere positivo.
3.2.	Si chiede se sia possibile inviare una send_conclusion mentre la pratica è in attesa di integrazione da parte del richiedente, quindi subito dopo aver effettuato una request_integration ma prima che questa sia stata soddisfatta.
4.	retry: In merito allo scambio retry come descritto dal workflow RETRY-001
4.1.	si chiede in generale una spiegazione sull’ambito di applicazione di questo flusso 
4.1.1.	quando può esserci da parte dell’Ente Terzo la richiesta di una Retry? Presumiamo sia un’operazione manuale effettuata dall’operatore dell’Ente Terzo.
4.1.2.	se possibile chiediamo qualche esempio in cui l’Ente Terzo ne sia coinvolto sia nella ricezione che nell’invio della Retry.
4.2.	si chiede un esempio di chiamate con relativi url, body e response:
4.2.1.	di un’operazione che fallisce (rilevata incoerenza tra i dati ricevuti)
4.2.2.	del nuovo tentativo corretto della stessa operazione fallita al punto precedente.

**Comment by FCiminelliACN** [comment]
Si ricorda che la piattaforma GitHub è stata creata con lo scopo di gestire le proposte di aggiornamento e miglioramento delle Specifiche Tecniche. Tali proposte possono essere create solamente dai membri del Gruppo Tecnico, costituito come indicato dal decreto interministeriale del 26 settembre 2023 SUAP (pubblicato in Gazzetta ufficiale n. 276 del 25 novembre 2023).

Considerata la natura della segnalazione, la invitiamo a riproporla negli opportuni canali di supporto gestiti da InfoCamere.
