### ISSUE TITLE
Richiesta Info: Catalogo SSU

### ISSUE THREAD

**Issue by ARIA-DMontedoro** [AgID/specifiche-tecniche-DPR-160-2010#137]
Amministrazione competente
In merito al campo competent_administration presente nell’instanceDescriptor:
1.	Nella RequestIntegrationRequest, il campo integration_list.integration_request.requester_administration ha la stessa struttura della competent_administration. Si chiede perché, da una chiamata operata da noi Ente Terzo sia necessario specificare il campo testuale description all’interno di questo oggetto. Questo oggetto dev’essere riportato così com’è valorizzato sul relativo usecase_proceeding del instanceDescriptor?

InstanceDescriptor
Nel contesto dell’oggetto InstanceDescriptor:
1.	L’InstanceDescriptor, sul campo times riporta i campi max_integration_request e max_integration_response, dobbiamo assumere che siano già definiti ed immutabili quando l’istanza arriva all’Ente Terzo oppure vengono ridefiniti in fase di richiesta di integrazione?
2.	Entrambi gli oggetti instance e activity_model fanno riferimento ad un file (strutturato o meno), qual è la differenza di contenuto tra i due?

Documenti ed allegati
Al fine di poter estrarre informazioni di contenuto sulla pratica:
1.	si chiede se si può far riferimento al file strutturato suap.xml, e si chiede conferma che esso abbia una struttura fissa e standardizzata indipendentemente dal tipo di pratica.

**Comment by FCiminelliACN** [comment]
AgID ha reso disponibile una piattaforma di Help Desk (https://uniticket.agid.gov.it/tickets/new/agid-suap) dedicata alle Regioni e ai loro partner tecnologici al fine di dare risposte sugli eventuali dubbi delle Specifiche Tecniche.
Risultano essere attive delle utenze per l'ente ARIA S.p.A. a seguito della richiesta inviata ad AgID, pertanto, la invitiamo a caricare la presente richiesta su tale sistema di supporto.

Si ricorda inoltre che la piattaforma GitHub è stata creata con lo scopo di gestire le proposte di aggiornamento e miglioramento delle Specifiche Tecniche. Tali proposte possono essere create solamente dai membri del Gruppo Tecnico, costituito come indicato dal decreto interministeriale del 26 settembre 2023 SUAP (pubblicato in Gazzetta ufficiale n. 276 del 25 novembre 2023).
