### ISSUE TITLE
audit responsability of Catalogo SSU

### ISSUE THREAD

**Issue by vintra73** [AgID/specifiche-tecniche-DPR-160-2010#22]
il Catalogo SSU DEVE registrare tutti gli eventi inoltrati dalle componenti a prescindere dal rispetto dei termini e della corretta esecuzione dei flow, sia il rispetto dei tempi che della corretta esecuzione dei flow restano nelle responsabilità della comonente back-office che sta orchestrando la specifica istanza

**Comment by luigi-colella-IC** [comment]
Come previsto dalle specifiche tecniche, ciascuna componente telematica di un SUAP (FO e BO) o di un Ente Terzo, deve notificare al Catalogo tutti gli eventi di comunicazione in ingresso ed in uscita attivati nel corso della gestione istruttoria di una istanza. Per alcuni di essi, il descrittore dell'istanza, fissa i termini temporali entro i quali devono essere notificati (es richiesta integrazione documentale, richiesta indizione conferenza di servizi, indizione conferenza di servizi, parere positivo o negativo da parte dell'ente, ecc...). Tali tempi sono definiti nel descrittore dell'istanza dalla componente di Back Office. Se un evento di comunicazione verso il Catalogo dovesse essere notificato con ritardo ed il Catalogo dovesse rifiutarlo, rischiamo che il Catalogo se lo perda, generando una incoerenza tra attività eseguite dalle componenti SUAP ed ET ed attività registrate dal Catalogo, soprattutto perchè le attività vengono registrate solo dopo essere state eseguite. Essendo il Catalogo la componente incaricata della "registrazione" degli eventi di avanzamento istruttorio dell'istanza, sarebbe opportuno indipendentemente dall'istante in cui viene notificato, ed eventualmente rispondere alla componente mittente con un warning.

**Comment by vintra73** [comment]
@luigi-colella-IC dalla lettura delle specifiche tecniche non si ravveda una responsabilità da parte del Catalogo SSU relativamente al controllo dei tempi dei procedimenti

condivido la possibilità di aggiornare le response dei path /audit resi disponibili dal Catalogo SSU alle componenti (Front-Office, Back-Office e ET) aggiornando l'attuale OKRequest da ACK a struttura decorata con attibuto per segnalare eventuali warningcome proposto.

**Comment by LeonardoBorselli** [comment]
La funzione è strutturalmente inserita come facoltativa perché non necessaria allo svolgimento del procedimento amministrativo. In altri termini costituisce un appesantimento delle funzioni dell’amministrazione procedente e un potenziale punto di failure sotto la responsabilità dell’ente procedente non compensato da una semplificazione/vantaggio per l’ente stesso.

**Comment by vintra73** [comment]
per tutti i path */audit*
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4096598d0cdf3ad63ae1dfc62ea14a1da7db77d7/openAPI/catalogo-ssu_to_bo.yaml#L75
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4096598d0cdf3ad63ae1dfc62ea14a1da7db77d7/openAPI/catalogo-ssu_to_et.yaml#L50
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4096598d0cdf3ad63ae1dfc62ea14a1da7db77d7/openAPI/catalogo-ssu_to_fo.yaml#L51

cambiare 200 response da
```
OKRequest
```

a
```	
AuditResponse:
		type: object
		description: risposta audit
		required:
			- type			   
		properties:
			type:
				title: tipo messaggio
				type: string
				enum:
					- ok
					- warning
					- expected_time_exceeded
			message:
				title: messaggio
				type: string
```

**Comment by FCiminelliACN** [comment]
soluzione proposta con i seguenti commit sul branch AGID-FCIminelli:
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/commit/00271210f66df8e8a1c0da3927520ef5228eeb96
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/commit/dcb7b357b9ee81e68c6026fbf0147429bf908880

**Comment by pbecherini** [comment]
Mi chiedo se ha un valore aggiunto segnalare warning o expected_time_exceeded. Potrebbe complicare la componente catalogo che non si limiterebbe ad ricevere la notifica dell'evento, ma dovrebbe entrare in merito alle tempistiche. Questa "informazione" arriverebbe comunque dopo che l'evento si è verificato.
