### ISSUE TITLE
Funzionalità Human Oriented di creazione e modifica di uno sportello Suap o di un ente terzo

### ISSUE THREAD

**Issue by AltaUC** [AgID/specifiche-tecniche-DPR-160-2010#52]
Le specifiche tecniche descrivono ad alto livello i requisiti funzionali e non funzionali della componente Catalogo del Sistema informatico degli Sportelli Unici.

In riferimento alle funzionalità Human Oriented di creazione e modifica di uno sportello Suap o di un ente terzo, si osserva che nel nuovo modello architetturale le due tipologie di anagrafiche, nel corso della fase di accreditamento, vengono inserite nel Catalogo direttamente dal Sistema di accreditamento, per questa ragione non sembrerebbe più necessario prevederle nel Catalogo.

Resterebbero comunque garantite le funzionalità di ricerca delle stesse entità.

**Comment by vintra73** [comment]
In merito al tema in oggetto come AgID abbiamo effettuato l'analisi di impatto sugli oggetti che andrebbero aggiornati rilevando:
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/mantaince001/specifiche_navigabili/09_Requisiti%20funzionali%20e%20non%20funzionali%20Catalogo%20SSU/09_01/09_01_01/09_01_01.md
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/mantaince001/specifiche_navigabili/09_Requisiti%20funzionali%20e%20non%20funzionali%20Catalogo%20SSU/09_01/09_01_01/09_01_01_01.md
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/mantaince001/specifiche_navigabili/09_Requisiti%20funzionali%20e%20non%20funzionali%20Catalogo%20SSU/09_01/09_01_01/09_01_01_02.md

**Comment by nirubino** [comment]
proposed solution [#56 ](https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/56)
