### ISSUE TITLE
fixing rappresentazione protocollo general

### ISSUE THREAD

**Issue by vintra73** [AgID/specifiche-tecniche-DPR-160-2010#54]
corregere direzione flusso passo 20 di

https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/4096598d0cdf3ad63ae1dfc62ea14a1da7db77d7/sequence-diagram/General-001.mermaid#L50

e successivo aggiornamento:
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/main/image/sequence-diagram-general.png
- https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/main/image/sequence-diagram-general.svg

**Comment by FCiminelliACN** [comment]
Soluzione proposta con il seguente commit sul branch AGID-FCiminelli:
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/commit/4031e8deb9f6f6827e4cf0e5bc1cc824b5c2460a

manca solo da aggiornare i relativi png e svg

**Comment by FCiminelliACN** [comment]
Aggiornate le immagini nei formati png e svg:
https://github.com/AgID/specifiche-tecniche-DPR-160-2010/commit/a0ca08a91d8671b3e9d6ee5393b9c75020424fa6

**Comment by vintra73** [comment]
il GT approva la soluzione

**Comment by vintra73** [comment]
approvata dal GT il 07/03/2024
