### ISSUE TITLE
[ComUnica] - Recupero redirect URL per ridirezione del soggetto presentatore al portale SUAP

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#63]
Al momento, le specifiche tecniche non permettono una corretta ridirezione del soggetto presentatore, dal FO ComUnica al portale SUAP competente. Il sistema ComUnica dovrebbe avere a disposizione un servizio che, dato l’identificativo del comune, restituisca l’url del portale competente. In riferimento alle note dello schema BPMN, i portali dovranno anche gestire i parametri:
Codice fiscale: alfanumerico di 11 o 16 caratteri;
Codice univoco pratica ComUnica: alfanumerico max 20 caratteri
Il codice fiscale potrebbe non essere presente (caso di impresa in iscrizione). Il codice univoco pratica ComUnica invece sarà sempre presente. Nei parametri dovrebbe essere presente anche il codice del Comune per la gestione di soluzioni multi-tenant.

**Comment by luigi-colella-IC** [comment]
#74

**Comment by pbecherini** [comment]
L'URL con cui Comunica effettua il redirect dell'utente verso il FO del SUAP deve consentire al FO di verificare che i parametri non siano stati modificati. Da valutare se in questo scenario è necessario definire anche una validità temporale dell'URL di redirect.

**Comment by AnaclerioRiccardo** [comment]
Concordiamo la necessità di garantire l’identificazione del ComUnica quale sistema digitale che ha eseguito la redirect tramite un secret, tuttavia, trattandosi di un redirect non riteniamo necessaria l'aggiunta di un time-to-live.

Nell'OpenAPI "fo_to_cu" nello schema "FOPortal" https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/f1afd38f92dbfc946b67f88156b527a49006b7f3/openAPI/fo_to_cu.yaml#L365 suggeriamo di esplicitare che il codice fiscale è opzionale e di eliminare la properties di method e protocol in quanto implicite; inoltre ci chiediamo l'utilità di creare fluidità sul naming degli attributi che conterranno "municipality", "c_fiscale" e "instance_code_comunica"
