### ISSUE TITLE
[ComUnica] - Modifica parametri input servizio notify_receipt  al par. 8.4.1.2 “e-service Front-office SUAP per sistema ComUnica” delle specifiche tecniche

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#64]
si propone di aggiungere i campi di input del servizio notify_receipt (che permettere al sistema ComUnica di notificare l’avvenuto rilascio della ricevuta al Soggetto presentatore), prevedendo : 
- File distinta ComUnica xml: file di tipo .CUI.XML 
- File distinta ComUnica firmato: file .CUI.PDF.P7M (Firmato Cades) oppure file .CUI.PDF (firmato Pades, in ottica di evoluzione prevista, ma al momento ancora non gestita, dal sistema ComUnica)

**Comment by luigi-colella-IC** [comment]
#74

**Comment by AnaclerioRiccardo** [comment]
Suggeriamo di uniformare il naming della distinta comunica tra quello utilizzato nell' OpenAPI fo_to_cu https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/f1afd38f92dbfc946b67f88156b527a49006b7f3/openAPI/fo_to_cu.yaml#L219 (comunica-cui e comunica-cui-signed) e quello utilizzato all'interno di General index (COMUNICA_CUI_XML e COMUNICA_CUI_PDF)
