### ISSUE TITLE
Ricevuta avvenuta presentazione dell'istanza

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#65]
La competenza della generazione della ricevuta è affidata al Front Office SUAP che la condivide direttamente con il richiedente a valle del processo di compilazione, ma non sembra condividerla con il Back Office SUAP. Se così fosse il SUAP non avrebbe la possibilità di condividere la stessa con gli Enti Terzi e con il Fascicolo di impresa nonostante tale documento rappresenti un titolo abilitativo per le SCIA (art 14, comma 2 nuovo Allegato Tecnico DPR 160/2010)

**Comment by luigi-colella-IC** [comment]
#74

**Comment by AnaclerioRiccardo** [comment]
Suggeriamo di spostare lo schema generalIndex all'interno dell'instance-descriptor, questo non comporterebbe problemi di privacy perchè contiene solamente i riferimenti ai documenti e non il contenuto dello stesso

**Comment by luigi-colella-IC** [comment]
Il motivo per il quale l'oggetto generalIndex non è stato inserito nell'instanceDescriptor ma nelle API di comunicazione tra le componenti SUAP e ET è legato alla necessità di trasferire contenuti informativi trasversali rispetto ai moduli ed agli allegati dei procedimenti.

**Comment by MicheleRagnatela** [comment]
PL #84 
Aggiornato schema GeneralIndex nelle seguenti openAPI:
- bo_to_fo
- cu_to_fo
- et_to_bo
- ri_to_bo
