### ISSUE TITLE
Delta informativo tra SUAP.XML ed instanceDescriptor

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#67]
Il precedente allegato tecnico al DPR 160/2010 definiva la struttura del modello di riepilogo, meglio noto come SUAP.XML. Le specifiche tecniche di cui all'art. 5 del nuovo Allegato Tecnico al DPR 160/2010, invece, introducono il concetto di instanceDescriptor. Comparando i due descrittori emerge un delta di contenuto informativo che non sarebbe immediatamente nelle disponibilità del SUAP (es. dati dell'impresa, rappresentante legale, procura speciale, estremi del dichiarante, domicilio elettronico). Tali dati, correttamente non presenti nell'istanceDescriptor anche per ragioni di privacy (l'instanceDescriptor è detenuto dal Catalogo SSU e tale componente non tratta dati personali), sarebbero comunque importanti per la costruzione del dettaglio dell'istanza ricevuta e gestita dal SUAP e di conseguenza dagli Enti Terzi. Le stesse informazioni risulterebbero non disponibili al SUAP per colmare il debito informativo nei confronti del REA.

**Comment by luigi-colella-IC** [comment]
#74

**Comment by MicheleRagnatela** [comment]
PL #84 
Aggiornato schema GeneralIndex nelle seguenti openAPI:
- bo_to_fo
- cu_to_fo
- et_to_bo
- ri_to_bo
