### ISSUE TITLE
Debito informativo nei confronti del REA

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#68]
In riferimento al debito informativo nei confronti del REA, sarebbe necessario prevedere la possibilità da parte del Back Office SUAP di inoltrare con l'istanza, con l'integrazione documentale e con la chiusura il SUAP-REA.xml

**Comment by luigi-colella-IC** [comment]
#74

**Comment by MicheleRagnatela** [comment]
PL #84 
Aggiornato schema GeneralIndex nelle seguenti openAPI:
- bo_to_fo
- cu_to_fo
- et_to_bo
- ri_to_bo
