### ISSUE TITLE
Dati istanza e modello di attività

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#69]
Il precedente allegato tecnico al DPR 160/2010 prevedeva l'inclusione del modello di attività, meglio noto come MDA.XML, all'interno di una istanza SUAP per ogni fattispecie. Dall'analisi dell'instanceDescriptor, sembra che tale documento sia da associare all'attributo instance, considerato non obbligatorio. Probabilmente la non obbligatorietà è dovuta alla possibilità che il procedimento sia non strutturato. Se così fosse, in caso di procedimento non strutturato, un Front Office potrebbe inviare al Back Office una istanza priva dei modelli delle attività comportando l'impossibilità per il SUAP di disporre dei dati dell'istanza.

**Comment by AnaclerioRiccardo** [comment]
All'interno dell'istancedescriptor_schema e all'interno delle OpenAPI del catalogo SSU modificate nella pull request [issue 69](https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/75/files)
 nei path:
- "usecase_proceedings/instance/mime_type" 
- "usecase_proceedings/instance/activity_model/mime_type" 
suggeriamo di togliere l'enum al fine di garantire l'inserimento di un qualsiasi tipo di mime_type disponibile definito da "iana", dato che il file potrebbe essere sia strutturato che non strutturato e non si vuole limitare le amministrazioni all'utilizzo del formato.

Nei file "catalogoSSU_to_cu" e "catalogoSSU_to_ri" al path "usecase_proceedings/form" l'attributo schematron non deve essere required

**Comment by luigi-colella-IC** [comment]
Il modello di attività è già previsto in formato XML, quindi le piattaforme dovrebbero essere già in grado di generare l'MDA, sia per i procedimenti strutturati che per i procedimenti non strutturati, in questo formato senza ulteriori costi. Cambiare questo tipo di impostazione, potrebbe generare invece dei problemi sui gestionali di Back Office degli Enti che probabilmente hanno sostenuto degli investimenti per realizzare automatismi o logica di business a partire dall'interpretazione di questo specifico file.

**Comment by nirubino** [comment]
#80 rimosso il required sugli attrbuti schematron di form e attachment
