### ISSUE TITLE
Sospensione/conformazione in autorizzazione

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#70]
Il workflow di comunicazione tra SUAP ed Ente Terzo per la gestione delle istanze in regime amministrativo "autorizzativo" (ordinario - https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/mantaince001/sequence-diagram/DomandaAutorizzazione-001.mermaid) prevede la possibilità di richiedere sospensione/conformazione mentre dovrebbe essere possibile solo la richiesta di integrazione.

**Comment by luigi-colella-IC** [comment]
#74

**Comment by AnaclerioRiccardo** [comment]
Con l'eliminazione delle conclusioni di sospensione e conformazione è rimasta solamente la conclusione di positive_outcome e quindi non è più presente la possibilità di un esito negativo.

Con l'aggiunta del generalIndex suggeriamo di prevedere la possibilità di inviare i documenti di conclusione anche agli ET analogalmente come già previsto per il FO

**Comment by luigi-colella-IC** [comment]
@AnaclerioRiccardo si potrebbe pensare di aggiungere per l'oggetto TransferOutcomeNotifyMessage dell'e-service et_to_bo.yaml per l'attributo event il valore end_by_negative_outcome ?

**Comment by AnaclerioRiccardo** [comment]
PL https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/83
Consolidato il sequence diagram DomandaAutorizzazione inserendo la conclusione per esito negativo e la comunicazione al presentatore delle conclusioni del processo SUAP.
