### ISSUE TITLE
Comunicazione di chiusura istruttoria al REA

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#71]
In riferimento al /sequence-diagram/RI_InformationDebit-001.mermaid, l'Art. 2, comma 2 lett. b) della Legge 580/1993 - così come modificato dal d.Lgs 219/2016 definisce  il contenuto del fascicolo informatico d’impresa, ossia quel luogo deputato alla raccolta e conservazione del duplicato informatico “delle comunicazioni e dei documenti attestanti atti, fatti, qualità, stati soggettivi, degli atti di autorizzazione, di licenza, di concessione, di permesso o di nulla osta comunque denominati rilasciati dallo sportello unico per le attività produttive o acquisiti da altre amministrazioni ovvero comunicati dall'impresa o dalle agenzie per le imprese. Inoltre raccoglie e conserva le certificazioni di qualità o ambientali”.  Data la definizione del contenuto in cui vengono citati documenti propri della conclusione dell'iter istruttorio sembrerebbe necessaria la comunicazione di chiusura dell'iter stesso al repertorio economico amministrativo

**Comment by luigi-colella-IC** [comment]
#74

**Comment by AnaclerioRiccardo** [comment]
Manca la possibilità di un esito negativo della conclusione.
Inoltre nell'OpenAPI ri_to_bo al component NotifyMessage https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/f1afd38f92dbfc946b67f88156b527a49006b7f3/openAPI/ri_to_bo.yaml#L279 è necessario verificare che tutti gli stati conclusivi propagati da BO siano coerenti con quelli propagati al registro delle imprese; inoltre è opportuno spostare l'enum "end_by_negative_outcome" dalla component "NotifyMessage" alla component "TransferOutcomeNotifyMessage"
Nel sequence dyagram del debito informativo https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/f1afd38f92dbfc946b67f88156b527a49006b7f3/sequence-diagram/RI_InformationDebit-001.mermaid#L66 il riferimento al passo di DomandaAutorizzazione-001 è 93 anzichè 105

Con l'aggiunta del generalIndex suggeriamo di prevedere la possibilità di inviare i documenti di conclusione anche a RI analogalmente come già previsto per il FO

**Comment by luigi-colella-IC** [comment]
@AnaclerioRiccardo se spostiamo l'enum "end_by_negative_outcome" dalla component "NotifyMessage" alla component "TransferOutcomeNotifyMessage" dovremmo essere in grado di inviare il documento di conclusione anche a RI sia in caso di esito positivo (end_by_positive_outcome già previsto) che in caso di esito negativo. Corretto?

**Comment by AnaclerioRiccardo** [comment]
PL https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/83
Consolidato il sequence diagram RI_InformationDebit inserendo l'inoltro al RI delle differenti possibili conclusioni del processo SUAP
