### ISSUE TITLE
Black-box functionality test

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#77]
Al fine di consentire alla Suite di Black Box Test di verificare in autonomia (senza la necessità di molteplici interventi umani da parte del MIMIT e dei fornitori pubblici e privati delle PA) la conformità di una componente informatica di Front-office  SUAP, Back-office SUAP ed Enti Terzi  rispetto alle specifiche  tecniche  predisposte dal Gruppo tecnico di  cui al comma 3 dell'articolo 5, si suggerisce l'eliminazione dei casi test che prevedono esito TEST_ERROR_500 e TEST_ERROR_503 dalle tabelle dei paragrafi 8.6.1, 8.6.2, 8.6.3 delle sopra citate Specifiche Tecniche.

**Comment by AnaclerioRiccardo** [comment]
Sono da eliminare i casi di test che prevedono esito TEST_ERROR_500 e TEST_ERROR_503 anche nel file 08_06.md (https://github.com/AgID/specifiche-tecniche-DPR-160-2010/blob/mantaince001/specifiche_navigabili/08_e-service%20del%20SSU/08_06/08_06.md) alla tabella 30 e vanno eliminate le tabelle dalla 42 alla 51
