### ISSUE TITLE
modifica vincolo attributo legal_person instance_descriptor

### ISSUE THREAD

**Issue by nirubino** [AgID/specifiche-tecniche-DPR-160-2010#78]
L'attributo LEGAL_PERSON dell'instance descriptor attualmente prevede 9 numeri che non sono sufficienti a trasportare un numero di partita IVA, tale vincolo è da adeguare per permettere l'inserimento delle partite iva a 11 caratteri numerici  e dei codici fiscali da 16 caratteri

**Comment by AnaclerioRiccardo** [comment]
PL https://github.com/AgID/specifiche-tecniche-DPR-160-2010/pull/83
Aggiornata la porzione della regex delle entità legal_person nelle openAPI:
- catalogo-ssu_to_bo
- catalogo-ssu_to_cu
- catalogo-ssu_to_et
- catalogo-ssu_to_fo
- catalogo-ssu_to_ri
