### ISSUE TITLE
Richiesta integrazione da Ente Terzo

### ISSUE THREAD

**Issue by luigi-colella-IC** [AgID/specifiche-tecniche-DPR-160-2010#98]
Si evidenzia che allo stato attuale, l'ET non passa nel payload della richiesta di integrazione nessuna info che possa identificarlo (es. ipacode e officecode) che invece deve essere passata ad FO quando il BO deve notificare ad FO la presenza di richieste di integrazione.
Sarebbe opportuno che in bo_to_et.yaml venga aggiunta la sezione requester_administration nel metodo /request_integration che invece è presente in fo_to_bo.yaml  nel metodo /request_integration.
Di seguito si riportano i dettagli:

1) ET chiama BO con /request_integration in bo_to_et.yaml (manca sezione requester_administration)
{
  "cui": {
    "context": "string",
    "data": "2024-05-23",
    "progressivo": "string",
    "uuid": "string"
  },
  "instance_descriptor_version": "string",
  "integration_list": [
    {
      "code": "string",
      "ref": "string",
      "integration_request": "string"
    }
  ],
  "resource_id": "string",
  "hash": "string",
  "alg_hash": "S256"
}

2) BO chiama FO con /request_integration in fo_to_bo.yaml (la sezione requester_administration è presente)

{
  "cui": {
    "context": "string",
    "data": "2024-05-23",
    "progressivo": "string",
    "uuid": "string"
  },
  "instance_descriptor_version": "string",
  "integration_list": [
    {
      "code": "string",
      "ref": "string",
      "integration_request": [
        {
          "request": "string",
          "requester_administration": {
            "ipacode": "string",
            "officecode": "string",
            "version": "51157530",
            "description": "string"
          }
        }
      ]
    }
  ],
  "integration_document_list": [
    {
      "requester_administration": {
        "ipacode": "string",
        "officecode": "string",
        "version": "88m61055",
        "description": "string"
      },
      "resource_id": "string",
      "hash": "string",
      "alg_hash": "S256"
    }
  ]
}

**Comment by MassyCare99** [comment]
la blackBox in questi casi passerebbe

  "integration_list" : [ {
    "code" : "USEC-0000224",
    "ref" : 1,
    "integration_request" : [ {
      "request" : "Descrizione Richiesta",
      "requester_administration" : {
        "ipacode" : "IPA_LOC_6",
        "officecode" : "code_LOC_6",
        "version" : "00.00.00",
        "description" : "Ente Comune fittizio locale"
      }
    } ]
  } ],
